import { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import api from "../lib/appwrite";

export default function Home() {
  const [projects, setProjects] = useState([]);
  useEffect(() => {
    api
      .listDocuments(process.env.NEXT_PUBLIC_APPWRITE_PROJECT_COLLECTION)
      .then((response) => {
        // console.log(response);
        setProjects([...response.documents.reverse()]);
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Appwrite app</h1>
      {projects.map((article, index) => {
        return (
          <div key={index}>
            <h1>{article.title}</h1>
            <p>{article.description}</p>
          </div>
        );
      })}
    </div>
  );
}
